_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("doclaynet_train",)
  TEST:  ("doclaynet_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
